import test from "node:test";
import assert from "node:assert/strict";
import {TOTAL_WAVES,UNITS,WAVE_PLAN,linkedTo,createRun,placeUnit,upgradeUnit,sellUnit,startWave,spawnEnemy,castSpell,chooseUpgrade,draftChoices,tick} from "../dist/games/mushroom-keep/rules.js";

test("mushroom keep only deploys on free plots and charges coins",()=>{const state=createRun();assert.equal(placeUnit(state,"ranger",1,1),true);assert.equal(state.coins,12-UNITS.ranger.cost);assert.equal(placeUnit(state,"knight",1,1),false);assert.equal(placeUnit(state,"knight",2,3),false);assert.equal(state.units.length,1)});
test("units can be upgraded and sold only while preparing",()=>{const state=createRun();placeUnit(state,"knight",1,1);assert.equal(upgradeUnit(state,state.units[0].id),true);assert.equal(state.units[0].level,2);assert.equal(sellUnit(state,state.units[0].id),true);assert.equal(state.units.length,0);startWave(state);assert.equal(placeUnit(state,"knight",3,1),false)});
test("waves spawn enemies and the final wave includes a boss",()=>{const state=createRun();assert.equal(startWave(state),true);for(let i=0;i<5;i++)tick(state,.05);assert.equal(state.enemies.length,1);assert.equal(state.wave,1);state.phase="build";state.wave=TOTAL_WAVES-1;assert.equal(startWave(state),true);assert.equal(state.queue.at(-1),"boss")});
test("spell damages nearby enemies with hit feedback and observes cooldown",()=>{const state=createRun();startWave(state);spawnEnemy(state,"armor");assert.ok(state.effects.some(fx=>fx.type==="spawn"));const before=state.enemies[0].hp;assert.equal(castSpell(state,.5,3.5),true);assert.ok(state.enemies[0].hp<before);assert.ok(state.enemies[0].hit>0);assert.equal(castSpell(state,.5,3.5),false)});
test("upgrade draft has distinct choices and applies a build-changing reward",()=>{const state=createRun();const choices=draftChoices(()=>0);assert.equal(new Set(choices.map(item=>item.id)).size,3);state.phase="reward";state.choices=choices;assert.equal(chooseUpgrade(state,"pierce"),true);assert.equal(state.mods.pierce,true);assert.equal(state.phase,"build")});
test("linked knights pierce and linked mages shatter frozen enemies",()=>{const attack=(covered,frozen)=>{const state=createRun();placeUnit(state,"ranger",3,4);if(covered)placeUnit(state,"knight",1,4);if(frozen)placeUnit(state,"mage",3,3);state.phase="battle";state.wave=1;spawnEnemy(state,"armor");const enemy=state.enemies[0];enemy.segment=5;enemy.progress=0;if(frozen)enemy.slow=1;const before=enemy.hp;tick(state,.01);return before-enemy.hp};const plain=attack(false,false),cover=attack(true,false),combo=attack(true,true);assert.ok(cover>plain);assert.ok(combo>cover)});
test("an unguarded castle eventually falls",()=>{const state=createRun();state.hearts=1;startWave(state);for(let i=0;i<2000&&state.phase==="battle";i++)tick(state,.05);assert.equal(state.phase,"lost")});
test("a strong defense can complete the six-wave campaign",()=>{const state=createRun();state.units=[{id:1,type:"ranger",x:1,y:1,level:3,cooldown:0},{id:2,type:"mage",x:5,y:2,level:3,cooldown:0},{id:3,type:"ranger",x:7,y:3,level:3,cooldown:0},{id:4,type:"knight",x:9,y:4,level:3,cooldown:0}];state.mods.ranger=4;state.mods.mage=4;for(let wave=1;wave<=TOTAL_WAVES;wave++){assert.equal(startWave(state),true);for(let frame=0;frame<3500&&state.phase==="battle";frame++)tick(state,.05);assert.notEqual(state.phase,"battle");if(state.phase==="reward")assert.equal(chooseUpgrade(state,state.choices[0].id),true)}assert.equal(state.phase,"won")});
test("six waves introduce distinct enemy counters and a finale",()=>{assert.equal(TOTAL_WAVES,6);assert.equal(WAVE_PLAN.length,6);assert.ok(WAVE_PLAN[1].types.includes("bat"));assert.ok(WAVE_PLAN[2].types.includes("armor"));assert.ok(WAVE_PLAN[3].types.includes("sapper"));assert.equal(WAVE_PLAN[5].types.at(-1),"boss")});
test("different professions link only while neither is jammed",()=>{const state=createRun();placeUnit(state,"knight",1,1);placeUnit(state,"ranger",3,1);assert.equal(linkedTo(state,state.units[0],"ranger"),true);state.units[1].jam=2;assert.equal(linkedTo(state,state.units[0],"ranger"),false)});
test("linked attacks create a visible combo cue",()=>{const state=createRun();placeUnit(state,"ranger",3,4);placeUnit(state,"knight",1,4);state.phase="battle";state.wave=1;state.queue=["slime"];spawnEnemy(state,"armor");state.enemies[0].segment=5;tick(state,.05);assert.ok(state.effects.some(fx=>fx.type==="combo"&&fx.label==="贯穿"));assert.ok(state.units.some(u=>u.linkGlow>0))});
test("sapper disables nearby units but the effect expires",()=>{const state=createRun();placeUnit(state,"ranger",3,3);state.phase="battle";state.wave=4;spawnEnemy(state,"sapper");const enemy=state.enemies[0];enemy.segment=4;enemy.pulse=0;for(let i=0;i<16;i++)tick(state,.05);assert.ok(state.units[0].jam>0);state.enemies=[];state.queue=["slime"];for(let i=0;i<50;i++)tick(state,.05);assert.equal(state.units[0].jam,0)});
test("sapper warns before cutting a nearby link",()=>{const state=createRun();placeUnit(state,"ranger",3,3);state.phase="battle";state.wave=4;spawnEnemy(state,"sapper");const enemy=state.enemies[0];enemy.segment=4;enemy.pulse=0;tick(state,.05);assert.equal(enemy.intent.kind,"sapper");assert.equal(state.units[0].jam,0);for(let i=0;i<15;i++)tick(state,.05);assert.ok(state.units[0].jam>0)});
test("boss announces alternating attacks and a meteor can interrupt either",()=>{const state=createRun();state.phase="battle";state.wave=6;state.queue=["slime"];spawnEnemy(state,"boss");const boss=state.enemies[0];boss.abilityClock=.01;tick(state,.05);assert.equal(boss.intent.kind,"howl");const position=()=>({x:.5+boss.segment+boss.progress,y:3.5});assert.equal(castSpell(state,position().x,position().y),true);assert.equal(boss.intent,null);assert.ok(boss.stun>0);assert.equal(state.interrupts,1);assert.ok(state.effects.some(fx=>fx.type==="interrupt"));state.spellCooldown=0;boss.abilityClock=.01;tick(state,.05);assert.equal(boss.intent.kind,"rush");assert.equal(castSpell(state,position().x,position().y),true);assert.equal(state.interrupts,2)});
test("uninterrupted boss howl jams defenders while rush advances along the path",()=>{const state=createRun();placeUnit(state,"knight",1,4);state.phase="battle";state.wave=6;state.queue=["slime"];spawnEnemy(state,"boss");const boss=state.enemies[0];boss.segment=1;boss.progress=0;boss.abilityClock=.01;for(let i=0;i<35;i++)tick(state,.05);assert.ok(state.units[0].jam>0);boss.abilityClock=.01;for(let i=0;i<3;i++)tick(state,.05);assert.equal(boss.intent.kind,"rush");const before=boss.segment+boss.progress;for(let i=0;i<28;i++)tick(state,.05);assert.ok(boss.segment+boss.progress>before+1)});
